### ISSUE TITLE
SUGGESTION: Input boxes & Application Descriptions

### ISSUE THREAD

**Issue by OnyxEye-RCG** [ezAppsDev/Application-System#6]
1. Not sure if it's possible, but I can see this being more admin friendly if input boxes could be added rather than one big text box.

2. On the section where the application format is entered, a "description" field would be nice. So information can be given to the applicant prior to them entering anything. For example: "IMPORTANT! In order to be considered for any whitelisted civilian job, you MUST meet the following Requirements before an application will be viewed/considered:

- Minimum 16 Years of Age at time of application
- Have joined the Discord: (redacted)
- Have a microphone that works well and is adjusted properly
- Have attended a minimum of 5 community RP nights within a 30 day period. (Tues and Sat nights at 9PM EST) *Attendance is tracked through a player logging system

**Comment by Jonah412** [comment]
Upvote!

**Comment by tyler-wp** [comment]
Input boxes is something that I’m not personally sure how to do and integrate efficiently. It may come in the future, but currently is not planned. 

Application descriptions is planned although and should be in before release.
